package com.customjewelry.repository;

import com.customjewelry.model.Jewelry;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface JewelryRepository extends MongoRepository<Jewelry, String> {

    // Custom finder methods (Spring generates the implementation automatically!)

    // Find jewelry by type (e.g., "Ring")
    List<Jewelry> findByType(String type);

    // Find jewelry by material (e.g., "Gold")
    List<Jewelry> findByMaterial(String material);

    // Find designs generated by a specific prompt keyword
    List<Jewelry> findByAiImagePromptContaining(String keyword);
}